# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.8
    hooks:
        # Run the linter.
    - id: ruff
      args: [ --fix ]
      # Run the formatter.
    - id: ruff-format
# -   repo: local
#     hooks:
#     - id: unittest-check
#       name: unittest-check
#       entry: python -m coverage run -m unittest discover
#       args: ["-v", "-s", "./tests", "-p", "*test*.py"]
#       pass_filenames: false
#       language: system
#       'types': [python]
#       stages: [commit]
#     - id: unittest-coverage
#       name: unittest-coverage
#       entry: python -m coverage report --fail-under=70
#       pass_filenames: false
#       #additional_dependencies: [coverage]
#       language: system
#       #language: system
#       stages: [commit]
